#ifndef MATERIALRESOURCES_H_
#define MATERIALRESOURCES_H_

#include <stdint.h>

extern "C" {
    extern const uint8_t MATERIALRESOURCES_PACKAGE[];
    extern int MATERIALRESOURCES_AIDEFAULTMAT_OFFSET;
    extern int MATERIALRESOURCES_AIDEFAULTMAT_SIZE;
}
#define MATERIALRESOURCES_AIDEFAULTMAT_DATA (MATERIALRESOURCES_PACKAGE + MATERIALRESOURCES_AIDEFAULTMAT_OFFSET)

#endif
